title: "Arunas Mazeika"
description: "Web Developer in Nantes, France"
about: "I'm a backend web developer passionate about code who likes to spend his time writing things for the web. While advocating re-factoring above all I also believe that writing simple and clean code is the key for creating great software. Less is MORE! and cats are evil creatures"
location: "Nantes, France"
#email: me@arunasmazeika.com
baseurl: ""

url: "http://www.arunasmazeika.com" # replace by your site's url
twitter_username: arunasmazeika
github_username:  amazeika
spotify_username: arunasmazeika
skype_username: arunas_mazeika
linkedin_username: arunasmazeika
facebook_username: amazeika
author: "Arunas Mazeika"

# google analytics tracking code, please change the value
g_analytics: ""

# add your disqus to enable comments
disqus_shortname:

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
#projects_btn: "Projects"
#posts_btn: "Posts"
#imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
